### ISSUE TITLE
U+2019 inside file menu list causes segfault

### ISSUE THREAD

**Issue by mattlohkamp** [Chasyxx/chtracker#1]
' and \` work fine but ’ (aka [right single quotation mark](https://en.wikipedia.org/wiki/Right_single_quotation_mark)) does not!

to reproduce:

1. create a file at `c:\’.txt`
2. open chtracker
3. hit F7 to navigate to the file menu
4. crash

**Comment by Chasyxx** [comment]
’ also causes freeze on Linux. Simply open a folder with a file/folder/directory with the `’` character inside. Might have to use `wstring` (unicode-capable) instead of `string`

**Comment by Chasyxx** [comment]
Seems to work with other unicode characters too (Э also did the trick)

**Comment by Chasyxx** [comment]
Ok, i'll work on resolving this soon. I think i've figured out the issue:
1. The unicode character is actually read as multiple bytes/characters (not an actual problem)
2. Each character seems to be assigned an invalid index into the font (this is the critical part)
3. Program reads out of bounds in the font
4. Segmentation fault
