### ISSUE TITLE
bug: saving appends an additional 's' to the file extension in windows

### ISSUE THREAD

**Issue by mattlohkamp** [Chasyxx/chtracker#2]
to reproduce:

1. open chtracker
2. press F7 to access the file menu
3. save a file using the default filename at at `c:\test\` ('test' subdir avoids windows' security preventing the user from accessing the root of boot drive) - will result in `c:\test\file.chts`
4. press F7 again to return to the file menu
5. hit 's' to save the file again
6. see that the suggested filename is now `file.chtss`
7. repeat steps 4-6 as often as you like to append additional 's' characters (e.g. `file.chtsss` etc.)

guessing it's grabbing the 's' keypress you use to navigate to the save view, and adding it to the filename? and guessing that the file extension is intended to be `.cht` only?

**Comment by Chasyxx** [comment]
Save and render menus are now entered on keyup. The letter is no longer added
