### ISSUE TITLE
bug: rendering an empty project causes crash on windows

### ISSUE THREAD

**Issue by mattlohkamp** [Chasyxx/chtracker#3]
reproduce:

1. start chtracker
2. hit F7 for file menu
3. navigate to `c:\test\`
4. hit 'r' to render, 'enter' to confirm
5. program crashes

**Comment by Chasyxx** [comment]
The crash was a result of an `std::out_of_range` exception when the program attempts to read from the first (nonexistent in this case) instrument to figure out how long a pattern is. r key no longer works without instruments
