### ISSUE TITLE
bug: distorted sound glitch on playback begin / end (windows)

### ISSUE THREAD

**Issue by mattlohkamp** [Chasyxx/chtracker#5]
once playback begins, pressing 'enter' again to stop playback results in a loud distorted glitchy sound

to reproduce:

- start a new project
- add an instrument (square) and a note (C4) to the pattern
- press 'enter' to start playback, press 'enter' again to stop playback

see attached for resulting sound - [untitled.zip](https://github.com/Chasyxx/chtracker/files/15125795/untitled.zip)

**Comment by Chasyxx** [comment]
Already fixed in [this existing commit](https://github.com/Chasyxx/chtracker/commit/8bb8c153cf94a5850043be802699455b6b265ca9).
